import type { Metadata } from "next";
import MainProvider from "@/provider/MainProvider";
import "../assets/font/font.css";
import "./globals.scss";

export const metadata: Metadata = {
  title: "На лодку",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
